`timescale 1ns / 1ps
// =====================================================================
//  tb_top_known.v  —  Testbench with a KNOWN digit image
// =====================================================================
//  Unlike tb_top.v (which sends a synthetic ramp that is NOT a real
//  digit), this testbench loads a real MNIST test image directly into
//  the FPGA's image RAM via $readmemh, runs the full compute pipeline,
//  and compares the predicted digit against the image's known label.
//
//  HOW TO USE:
//  1. Generate the image .mem files first:
//         cd python
//         python export_test_image_mem.py
//     This creates sim/test_image_0.mem .. sim/test_image_9.mem
//     and sim/test_image_labels.txt (listing each image's label).
//
//  2. Pick which image to test. The first 10 MNIST test labels are:
//         index 0 -> 7     index 5 -> 1
//         index 1 -> 2     index 6 -> 4
//         index 2 -> 1     index 7 -> 9
//         index 3 -> 0     index 8 -> 5
//         index 4 -> 4     index 9 -> 9
//
//  3. Edit the two localparams below to match your chosen image:
//         IMAGE_FILE      = "test_image_3.mem"
//         EXPECTED_LABEL  = 0
//
//  4. Set tb_top_known.v as the simulation top and Run Behavioral
//     Simulation.  The console will print:
//         PASS: predicted N == expected M
//     or
//         FAIL: predicted N != expected M
//
//  NOTE: This testbench preloads image_ram directly and forces
//  loading_done=1 to skip the slow 784-byte UART transfer (~68ms of
//  sim time). The full compute pipeline (conv1 + pool1 + conv2 +
//  pool2 + fc) still runs in full — only the UART load is bypassed
//  for speed. If you want to test the UART path too, use tb_top.v
//  (but note that tb_top.v sends a synthetic ramp, not a real digit).
// =====================================================================
module tb_top_known;
    reg clk = 0;
    reg btnC = 1;
    reg RsRx = 1;                      // idle-high; we don't send UART here
    wire [3:0] an;
    wire [6:0] seg;
    wire [15:0] led;

    // -----------------------------------------------------------------
    // >>> EDIT THESE TWO LINES TO PICK THE IMAGE YOU WANT TO TEST <<<
    // -----------------------------------------------------------------
    localparam IMAGE_FILE     = "test_image_0.mem";   // generated by export_test_image_mem.py
    localparam integer EXPECTED_LABEL = 7;            // MNIST test image 0 is a "7"

    top dut (
        .clk(clk), .btnC(btnC), .RsRx(RsRx),
        .an(an), .seg(seg), .led(led)
    );

    always #5 clk = ~clk;   // 100 MHz

    integer i;
    initial begin
        // ---------- Hold reset ----------
        btnC = 1;
        #200;
        btnC = 0;
        #200;

        // ---------- Preload image RAM directly (bypasses UART) ----------
        // Hierarchical reference into the DUT's image_ram.mem array.
        // The .mem file has 784 hex bytes in raster order, matching
        // exactly what the UART path would have written.
        $readmemh(IMAGE_FILE, dut.image_ram.mem);

        // ---------- Force loading_done to kick the FSM past M_LOAD ----------
        // Without this, the master FSM sits in M_LOAD forever waiting for
        // 784 UART bytes. Forcing loading_done=1 for a few cycles lets it
        // transition to M_CONV1 and start the real compute pipeline.
        // (The auto-restart logic in top.v would reset loading_done on a
        // new UART byte, but since we send no UART bytes here, the force
        // is safe for a single-image test.)
        force dut.loading_done = 1'b1;
        #20;
        release dut.loading_done;

        // ---------- Wait for result_ready (led[4]) ----------
        // The full pipeline (conv1 + pool1 + conv2 + pool2 + fc) takes
        // on the order of a few hundred thousand cycles at 100 MHz,
        // i.e. a few ms of sim time. Give a generous 50 ms timeout.
        wait (led[4] == 1'b1);

        // ---------- Report ----------
        $display("");
        $display("=========================================================");
        $display(" Image file      : %0s", IMAGE_FILE);
        $display(" Expected label  : %0d", EXPECTED_LABEL);
        $display(" Predicted digit : %0d   (shown on led[3:0])", led[3:0]);
        $display("---------------------------------------------------------");
        if (led[3:0] == EXPECTED_LABEL[3:0])
            $display(" PASS: prediction matches the known label");
        else
            $display(" FAIL: prediction does NOT match the known label");
        $display("=========================================================");

        #1000;
        $finish;
    end

    // ---------- Safety timeout ----------
    initial begin
        #50_000_000;   // 50 ms wall-sim time
        $display("TIMEOUT: pipeline never finished (led[4] never went high)");
        $display("  Check that the .mem file exists and the FSM is advancing.");
        $finish;
    end
endmodule
